name: execution_workspace
description: 
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  interactive:
    path: ../interactive
  # example 3rd party lib
  path: ^1.8.2

dev_dependencies:

